version: "3"
services:
    sponsor-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: sponsor-service
        restart: always
        env_file:
            - .env
        networks:
            - my-net
        depends_on:
            - psql-sponsors
        command: npm run dev
    psql-sponsors:
        image: postgres
        container_name: psql-sponsors
        environment:
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        # volumes:
        #     - ./sql/initialize_database.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my-net
networks:
  my-net:
    external:
      name: my-net
